language: java
jdk: oraclejdk8
# Run on a dedicated Trusty VM to avoid random problems like "User limit of inotify watches reached"
sudo: required
dist: trusty

before_install:
  # Disable all Travis default repositories
  - sed -i "s/activeByDefault>true</activeByDefault>false</g"  ~/.m2/settings.xml

script:
  - mvn -B -e -V clean verify

# Cache requires a master build
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
before_cache:
  # remove all build artifacts
  - rm -rf $HOME/.m2/repository/com/vaadin/flow
  - rm -rf $HOME/.m2/repository/com/vaadin/flow-*

